// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA0Pq5Lb0C4xk5fimxuP3yz4g_tSf56q2Q',
    appId: '1:702940862373:web:25d79ca273371756333a4c',
    messagingSenderId: '702940862373',
    projectId: 'lcapp-6773b',
    authDomain: 'lcapp-6773b.firebaseapp.com',
    storageBucket: 'lcapp-6773b.firebasestorage.app',
    measurementId: 'G-20BF7Y8NFG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDGeoLDOhdKsVfMCmb81p7GiLnzHad56aA',
    appId: '1:702940862373:android:a1d69625b4bf5cc1333a4c',
    messagingSenderId: '702940862373',
    projectId: 'lcapp-6773b',
    storageBucket: 'lcapp-6773b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAxLqYlIaVkJ9Fv5wLFRBinh_f2dyIfoGI',
    appId: '1:702940862373:ios:cebd253b3420f579333a4c',
    messagingSenderId: '702940862373',
    projectId: 'lcapp-6773b',
    storageBucket: 'lcapp-6773b.firebasestorage.app',
    iosBundleId: 'com.example.productivityProgramV1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAxLqYlIaVkJ9Fv5wLFRBinh_f2dyIfoGI',
    appId: '1:702940862373:ios:cebd253b3420f579333a4c',
    messagingSenderId: '702940862373',
    projectId: 'lcapp-6773b',
    storageBucket: 'lcapp-6773b.firebasestorage.app',
    iosBundleId: 'com.example.productivityProgramV1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA0Pq5Lb0C4xk5fimxuP3yz4g_tSf56q2Q',
    appId: '1:702940862373:web:f040f47fc9296a23333a4c',
    messagingSenderId: '702940862373',
    projectId: 'lcapp-6773b',
    authDomain: 'lcapp-6773b.firebaseapp.com',
    storageBucket: 'lcapp-6773b.firebasestorage.app',
    measurementId: 'G-YCNW3KEJKC',
  );
}
